name: Trigger every 15 mins

on:
  # Uncomment the following line if you want to trigger based on a schedule
  # schedule:
  #   - cron: '*/15 * * * *'  # Cron expression to trigger every 15 minutes
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout code
        uses: actions/checkout@v3

      # Install Android SDK
      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-win-6609375_latest.zip -O android-sdk.zip
          mkdir -p $HOME\Android\sdk
          tar xf android-sdk.zip -C $HOME\Android\sdk

      # Add Android SDK tools to PATH
      - name: Add Android SDK tools to PATH
        run: |
          echo "export PATH=$HOME\Android\sdk\cmdline-tools\latest\bin:$PATH" >> $PROFILE
          echo "export ANDROID_HOME=$HOME\Android\sdk" >> $PROFILE
          echo "export PATH=$ANDROID_HOME\emulator:$PATH" >> $PROFILE
          echo "export PATH=$ANDROID_HOME\platform-tools:$PATH" >> $PROFILE
        shell: bash

      # Install Emulator
      - name: Install Emulator
        run: sdkmanager --install emulator

      # Install System Images
      - name: Install System Images
        run: sdkmanager --install "system-images;android-29;default;x86_64"

      # Create AVD
      - name: Create AVD
        run: echo no | avdmanager create avd --force -n test --abi 'default/x86_64' --package 'system-images;android-29;default;x86_64' --device 'Nexus 6'

      # Start Emulator
      - name: Start Emulator
        run: emulator -avd test -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim
